# application.yml
spring:
  application:
    name: EcommerceStoreWeb

  datasource:
    url: jdbc:postgresql://localhost:5432/EcommerceStoreWeb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom application properties
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
  pagination:
    default-page-size: 10
    max-page-size: 100